// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0n5W4ONWItSErpqbw36mOuVvn5VYXA18',
    appId: '1:1039689433560:web:733ba839dbebd4bd56b2ad',
    messagingSenderId: '1039689433560',
    projectId: 'scholarship-app-32ff4',
    authDomain: 'scholarship-app-32ff4.firebaseapp.com',
    databaseURL: 'https://scholarship-app-32ff4-default-rtdb.firebaseio.com',
    storageBucket: 'scholarship-app-32ff4.firebasestorage.app',
    measurementId: 'G-FHJ9EPHZBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ4ur9uBXSh60YZvvMKxm1O6vy7cQkwpY',
    appId: '1:1039689433560:android:f7e6594e67e8284856b2ad',
    messagingSenderId: '1039689433560',
    projectId: 'scholarship-app-32ff4',
    databaseURL: 'https://scholarship-app-32ff4-default-rtdb.firebaseio.com',
    storageBucket: 'scholarship-app-32ff4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnfBa0vfyIj7gM8aoERCp9S6nyQ9_5PiM',
    appId: '1:1039689433560:ios:20077f1519ff127556b2ad',
    messagingSenderId: '1039689433560',
    projectId: 'scholarship-app-32ff4',
    databaseURL: 'https://scholarship-app-32ff4-default-rtdb.firebaseio.com',
    storageBucket: 'scholarship-app-32ff4.firebasestorage.app',
    iosBundleId: 'com.example.scholarshipapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnfBa0vfyIj7gM8aoERCp9S6nyQ9_5PiM',
    appId: '1:1039689433560:ios:20077f1519ff127556b2ad',
    messagingSenderId: '1039689433560',
    projectId: 'scholarship-app-32ff4',
    databaseURL: 'https://scholarship-app-32ff4-default-rtdb.firebaseio.com',
    storageBucket: 'scholarship-app-32ff4.firebasestorage.app',
    iosBundleId: 'com.example.scholarshipapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0n5W4ONWItSErpqbw36mOuVvn5VYXA18',
    appId: '1:1039689433560:web:fe9f1871ca18ce3d56b2ad',
    messagingSenderId: '1039689433560',
    projectId: 'scholarship-app-32ff4',
    authDomain: 'scholarship-app-32ff4.firebaseapp.com',
    databaseURL: 'https://scholarship-app-32ff4-default-rtdb.firebaseio.com',
    storageBucket: 'scholarship-app-32ff4.firebasestorage.app',
    measurementId: 'G-5KSPBTNZBZ',
  );
}
